// Add your music here. Put each audio file in `public/music/` (or use an
// existing public path) and add an object following the two examples below.
// `src` must start with `/`, for example: `/music/my-song.mp3`.
export const musicLibrary = [
  {
    id: 'maki-k-m',
    title: 'kahel na langit x Kailan? (The Cozy Cove Fest)',
    artist: 'Maki',
    album: 'kahel na langit',
    src: '/maki-k-m.mp3',
    duration: '3:18',
    artwork: 'from-fuchsia-500 via-violet-600 to-indigo-950',
    mood: 'Focus',
  },
  {
    id: 'multo',
    title: 'Multo (Extended) (The Cozy Cove Fest)',
    artist: 'Cup of Joe',
    album: 'The Loved One',
    src: '/multo.mp3',
    duration: '3:42',
    artwork: 'from-cyan-400 via-blue-600 to-violet-950',
    mood: 'Unwind',
  },
  {
    id: 'all-too-well-10-minute-version',
    title: 'All Too Well (10 Minute Version)',
    artist: 'Taylor Swift',
    album: 'Red (Taylor’s Version)',
    src: '/alltoowell10minutes-taylorswift.mp3',
    duration: '10:13',
    artwork: 'from-red-500 via-rose-700 to-amber-950',
    mood: 'Storytelling',
  },
  {
    id: 'anti-hero',
    title: 'Anti-Hero',
    artist: 'Taylor Swift',
    album: 'Midnights',
    src: '/anti-hero-taylorswift.mp3',
    duration: '3:20',
    artwork: 'from-slate-400 via-blue-700 to-indigo-950',
    mood: 'Late night',
  },
  {
    id: 'deja-vu',
    title: 'deja vu',
    artist: 'Olivia Rodrigo',
    album: 'SOUR',
    src: '/dejavu-oliviarodrigo.mp3',
    duration: '3:35',
    artwork: 'from-violet-500 via-purple-700 to-fuchsia-950',
    mood: 'Dreamy',
  },
  {
    id: 'drivers-license',
    title: 'drivers license',
    artist: 'Olivia Rodrigo',
    album: 'SOUR',
    src: '/drivers-license-oliviarodrigo.mp3',
    duration: '4:02',
    artwork: 'from-indigo-400 via-blue-700 to-slate-950',
    mood: 'Reflective',
  },
  {
    id: 'getaway-car',
    title: 'Getaway Car',
    artist: 'Taylor Swift',
    album: 'reputation',
    src: '/getawaycar-taylorswift.mp3',
    duration: '3:53',
    artwork: 'from-zinc-500 via-slate-700 to-black',
    mood: 'Energy',
  },
  {
    id: 'give-me-your-forever',
    title: 'Give Me Your Forever',
    artist: 'Zack Tabudlo',
    album: 'Episode',
    src: '/givemeyourforever-zacktabudlo.mp3',
    duration: '3:54',
    artwork: 'from-amber-300 via-orange-500 to-rose-800',
    mood: 'Romance',
  },
  {
    id: 'ilysb',
    title: 'ILYSB',
    artist: 'LANY',
    album: 'Make Out',
    src: '/ilysb-lany.mp3',
    duration: '3:31',
    artwork: 'from-pink-400 via-rose-600 to-purple-950',
    mood: 'Romance',
  },
  {
    id: 'palagi',
    title: 'Palagi',
    artist: 'TJ Monterde',
    album: 'Palagi',
    src: '/palagi-tjmonterde.mp3',
    duration: '3:29',
    artwork: 'from-emerald-400 via-teal-600 to-cyan-950',
    mood: 'Warm',
  },
  {
    id: 'photograph',
    title: 'Photograph',
    artist: 'Ed Sheeran',
    album: 'x',
    src: '/photograph-edsheeran.mp3',
    duration: '4:18',
    artwork: 'from-orange-400 via-amber-600 to-stone-950',
    mood: 'Memories',
  },
  {
    id: 'pulso',
    title: 'Pulso',
    artist: 'Zack Tabudlo',
    album: 'Pulso',
    src: '/pulso-zacktabudlo.mp3',
    duration: '4:03',
    artwork: 'from-cyan-400 via-sky-600 to-indigo-950',
    mood: 'Chill',
  },
  {
    id: 'shake-it-off',
    title: 'Shake It Off',
    artist: 'Taylor Swift',
    album: '1989',
    src: '/shake-it-off.mp3',
    duration: '3:39',
    artwork: 'from-sky-300 via-blue-500 to-indigo-800',
    mood: 'Energy',
  },
  {
    id: 'we-are-never-ever-getting-back-together',
    title: 'We Are Never Ever Getting Back Together',
    artist: 'Taylor Swift',
    album: 'Red',
    src: '/weareneverevergettingbacktogether.mp3',
    duration: '3:13',
    artwork: 'from-orange-500 via-red-600 to-rose-950',
    mood: 'Sing along',
  },
  {
    id: 'you-belong-with-me',
    title: 'You Belong With Me',
    artist: 'Taylor Swift',
    album: 'Fearless',
    src: '/youbelongwithme-taylorswift.mp3',
    duration: '3:51',
    artwork: 'from-yellow-300 via-amber-500 to-orange-900',
    mood: 'Nostalgic',
  },
]

export const featuredCollections = []
